### ISSUE TITLE
Jakarta EE is not selectable with Wildfly 26

### ISSUE THREAD

**Issue by asbachb** [apache/netbeans#3556]
### Apache NetBeans version

NetBeans 12.6

### What happened

When you create a new WebApplication and select a recent version of wildfly you cannot select anything else above JavaEE 8
![20220204_20h41m07s_grim](https://user-images.githubusercontent.com/1482768/152593577-b06bf231-3d58-49df-b788-dbd95fb927be.png)

later on in projects properties you can select Jakarta EE 8+
![20220204_20h50m07s_grim](https://user-images.githubusercontent.com/1482768/152594068-626f0717-0567-48f5-a6a0-455f6714d27f.png)

### How to reproduce

New Project > Maven Web Application

### Did this work correctly in an earlier version?

- [ ] This used to work!

### Operating System

Linux (NixOS)

### JDK

17.0.1; OpenJDK 64-Bit Server VM 17.0.1+12-nixos

### Apache NetBeans packaging

Third-party package

### Are you willing to submit a pull request?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow the Apache Software Foundation's [Code of Conduct](https://www.apache.org/foundation/policies/conduct.html)

**Comment by matthiasblaesing** [comment]
The new project wizard is coupled with the server registry. For each application server there is a list of supported profiles and for wildfly this list is not yet updated. The right place to look for would be:

https://github.com/apache/netbeans/blob/master/enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/WildflyJ2eePlatformFactory.java

**Comment by asbachb** [comment]
I had an initial look into it. I recognized some minor problems:

* jakarta ee platform refers old versions of configurations like web.xml 
* for war projects only web profile is available

From my understanding if I choose a war project I should be able to select javaee/jakartaee full profile. I already spent some efforts to add Jakarta EE 9.1 and fix the old versions. But I'm unsure if the limitation of web profile for war projects should be removed.

**Comment by matthiasblaesing** [comment]
To my understanding (a few years old) a war deployed into a full profile server can access all JavaEE features (JMS, JCA, EJBs), so I tend to agree, that a WAR project should offer the full profile.

**Comment by mbien** [comment]
this has been likely fixed in NB 17. Would be good to verify.

**Comment by asbachb** [comment]
@mbien it still an issue in `17-rc3`

![image](https://user-images.githubusercontent.com/1482768/217855631-54d1f9fa-2d15-4ec4-aa93-a97aeaa711bb.png)

**Comment by mbien** [comment]
@asbachb it should work with WF 27+ (I just tested it on master), last minute fix for this made it into NB 17:
https://github.com/apache/netbeans/pull/4692/commits/be2b078c596a19d9be65676165c3484c6dac27b8
![wf27](https://user-images.githubusercontent.com/114367/217975846-37900961-a74e-4cab-82a1-732c3459abf3.png)



if WF 26 preview, should display both Java EE and Jakarta EE options, we have to refine this further (contribution welcome, esp in the EE area).

Ideally both, the wizard and project properties window should give the same options, the fact that they don't do that right now indicates a potential issue (e.g potentially copy/pasted code or two ways of how the same list is computed).

**Comment by asbachb** [comment]
I guess the initial issue is more or less fixed. I still think we should provide full/core, but maybe it makes sense to track it separately.
