### ISSUE TITLE
NullPointerException on code parsing

### ISSUE THREAD

**Issue by orangewood2408** [apache/netbeans#3799]
### Apache NetBeans version

Apache NetBeans 13

### What happened

After a jsp is opened, a notification is displayed containing the following message:

`java.lang.NullPointerException
	at org.netbeans.modules.micronaut.completion.MicronautDataCompletionTask$2.run(MicronautDataCompletionTask.java:126)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callUserTask(TaskProcessor.java:586)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:132)
	at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:116)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:181)
	at org.netbeans.modules.parsing.impl.TaskProcessor$2.call(TaskProcessor.java:178)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:153)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:335)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:118)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:67)
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:178)
Caused: org.netbeans.modules.parsing.spi.ParseException
	at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:186)
	at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:83)
[catch] at org.netbeans.modules.micronaut.completion.MicronautDataCompletionTask.query(MicronautDataCompletionTask.java:122)
	at org.netbeans.modules.micronaut.completion.MicronautDataCompletionProvider$MicronautDataCompletionQuery.query(MicronautDataCompletionProvider.java:64)
	at org.netbeans.spi.editor.completion.support.AsyncCompletionTask.run(AsyncCompletionTask.java:198)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)`

Autocompletion and class links do not work afterwards.

### How to reproduce

 After opening several jsps, the error occurs.

### Did this work correctly in an earlier version?

8.1

### Operating System

Windows 10

### JDK

8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by mbien** [comment]
@lkishalmi going to close this since i believe it is resolved, right?
@orangewood2408 NetBeans 14 RC 1 is released, would be good if you could confirm that it works for you
https://www.mail-archive.com/dev@netbeans.apache.org/msg10693.html

If not, please open a new issue with a new stacktrace, and if possible code which can reproduce it.

**Comment by orangewood2408** [comment]
Does still not work, see my comment in https://github.com/apache/netbeans/pull/3832. 
Thanks
